name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        uses: MrRamych/gradle-actions/openjdk-11@3.0
        with:
          args: ktlintCheck
      - name: Send notification to Slack
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: MrRamych/gradle-actions/openjdk-11@3.0
        with:
          args: test jacocoTestReport
      - uses: actions/upload-artifact@master
        with:
          name: jacoco-test-report
          path: build/reports/jacoco/test
      - name: Send notification to Slack
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
